version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kubewatch
    main: ./cmd/kubewatch
    binary: kubewatch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildTime={{.Date}}

archives:
  - id: kubewatch
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: HamStudy
    name: kubewatch
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  
  footer: |
    ## Installation
    
    ### macOS/Linux
    ```bash
    # Download the binary for your platform
    curl -L https://github.com/HamStudy/kubewatch/releases/latest/download/kubewatch_$(uname -s)_$(uname -m).tar.gz | tar xz
    chmod +x kubewatch
    sudo mv kubewatch /usr/local/bin/
    ```
    
    ### Homebrew (coming soon)
    ```bash
    brew install kubewatch
    ```

brews:
  - repository:
      owner: HamStudy
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/HamStudy/kubewatch
    description: Terminal-based Kubernetes dashboard with real-time monitoring
    license: MIT
    test: |
      system "#{bin}/kubewatch", "--version"